project:
  type: default

format:
  revealjs:
    theme: default
    slide-number: true
    controls: true
    progress: true
    history: true
    transition: fade
    background-transition: fade
    center: false
    css: custom.scss
    width: 1440
    height: 900
    margin: 0.04
    chalkboard: false
    preview-links: auto

execute:
  echo: false
  warning: false
  error: false
